-- ==========================================
-- CREATE PRODUCTS TABLE
-- ==========================================
CREATE TABLE IF NOT EXISTS public.products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  slug TEXT UNIQUE NOT NULL,
  title_en TEXT NOT NULL,
  title_nl TEXT NOT NULL,
  description_en TEXT,
  description_nl TEXT,
  price NUMERIC(10, 2) NOT NULL,
  image TEXT,
  whatsapp_number TEXT,
  sort_order INT DEFAULT 0
);

-- Disable Row Level Security (RLS) to allow direct anonymous client queries (reads and updates)
ALTER TABLE public.products DISABLE ROW LEVEL SECURITY;

-- ==========================================
-- SEED INITIAL PRODUCTS
-- ==========================================
INSERT INTO public.products (slug, title_en, title_nl, description_en, description_nl, price, image, sort_order)
VALUES
(
  'moving-box-rent-set-of-10', 
  'Moving Box rent - Set of 10', 
  'Verhuisdoos huren - Set van 10', 
  'High quality, robust moving boxes for rent. Perfect for packing clothes, books, and heavy household items. Stackable and convenient.', 
  'Hoge kwaliteit, robuuste verhuisdozen te huur. Perfect voor het inpakken van kleding, boeken en zware huishoudelijke artikelen. Stapelbaar en handig.', 
  5.00, 
  'https://images.unsplash.com/photo-1595079676339-1534801ad6cf?auto=format&fit=crop&q=80&w=800', 
  1
),
(
  'book-box-rent-set-of-10', 
  'Book Box rent - Set of 10', 
  'Boekendoos huren - Set van 10', 
  'Sturdy book boxes designed specifically for heavy loads like books, documents, and files. Reinforced handles for comfortable carrying.', 
  'Stevige boekendozen speciaal ontworpen voor zware lasten zoals boeken, documenten en dossiers. Versterkte handvatten voor comfortabel dragen.', 
  5.00, 
  'https://images.unsplash.com/photo-1544947950-fa07a98d237f?auto=format&fit=crop&q=80&w=800', 
  2
),
(
  'tableware-paper-250-sheets', 
  'Tableware paper - 250 sheets', 
  'Inpakpapier servies - 250 vellen', 
  'Clean wrapping paper to protect your fragile glassware, plates, cups, and ceramic items from scratching and chipping during transport.', 
  'Schoon inpakpapier om uw breekbare glaswerk, borden, kopjes en keramische voorwerpen te beschermen tegen krassen en barsten tijdens transport.', 
  7.50, 
  'https://images.unsplash.com/photo-1589703900743-4b9dc632617a?auto=format&fit=crop&q=80&w=800', 
  3
),
(
  'bubble-wrap-1m-x-10m', 
  'Bubble wrap 1m x 10m', 
  'Noppenfolie 1m x 10m', 
  'High-grade protective bubble wrap for shielding fragile electronics, artwork, glassware, and other valuable items from impacts and vibration.', 
  'Hoogwaardige beschermende noppenfolie om breekbare elektronica, kunstwerken, glaswerk en andere waardevolle spullen te beschermen tegen stoten en trillingen.', 
  11.50, 
  'https://images.unsplash.com/photo-1589939705384-5185137a7f0f?auto=format&fit=crop&q=80&w=800', 
  4
),
(
  'mattress-cover-double-mattress', 
  'Mattress cover double mattress', 
  'Matrashoes tweepersoonsmatras', 
  'Heavy-duty, waterproof and dustproof protective plastic cover to keep your double mattress clean and dry during loading and transit.', 
  'Stevige, water- en stofdichte beschermende plastic hoes om uw tweepersoonsmatras schoon en droog te houden tijdens het laden en transporteren.', 
  4.95, 
  'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?auto=format&fit=crop&q=80&w=800', 
  5
),
(
  'roll-of-tape', 
  'Roll of tape', 
  'Rol tape', 
  'Premium strong adhesive packaging tape to securely lock moving boxes, bubble wrap, and wrapping papers. Durable and reliable.', 
  'Premium sterke verpakkingstape om verhuisdozen, noppenfolie en inpakpapier stevig te sluiten. Duurzaam en betrouwbaar.', 
  3.95, 
  'https://images.unsplash.com/photo-1607344645866-009c320b63e0?auto=format&fit=crop&q=80&w=800', 
  6
),
(
  'mattress-cover-single-mattress', 
  'Mattress cover single mattress', 
  'Matrashoes eenpersoonsmatras', 
  'Waterproof and dustproof protective plastic cover designed for single mattresses. Shields against moisture, dirt, and scuffing.', 
  'Water- en stofdichte beschermende plastic hoes ontworpen voor eenpersoonsmatrassen. Beschermt tegen vocht, vuil en slijtage.', 
  3.95, 
  'https://images.unsplash.com/photo-1540518614846-7eded433c457?auto=format&fit=crop&q=80&w=800', 
  7
),
(
  'wrapping-film-50cm-x-300m', 
  'Wrapping film 50cm x 300m', 
  'Stretchy wikkeltransferfolie - 50cm x 300m', 
  'Professional strength stretch wrap film for securing stacked items on pallets and shielding furniture surfaces from scratches and dust.', 
  'Professionele stretch wikkelbandfolie voor het vastzetten van gestapelde items op pallets en het beschermen van meubeloppervlakken tegen krassen en stof.', 
  13.95, 
  'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&q=80&w=800', 
  8
)
ON CONFLICT (slug) DO UPDATE
SET title_en = EXCLUDED.title_en,
    title_nl = EXCLUDED.title_nl,
    description_en = EXCLUDED.description_en,
    description_nl = EXCLUDED.description_nl,
    price = EXCLUDED.price,
    image = EXCLUDED.image,
    sort_order = EXCLUDED.sort_order;
